app:
  error_media: some.mp4
  auto_categories: false
  dirs:
    images: ./tmp/images
    working: ./tmp
    download: ./tmp/download
    categories:
      cat1: cat1
      cat2: cat2
telegram:
  token: ascascas
transmission:
  config:
    uri: http://127.0.0.1:9091
    user: user
    password: password
